FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV UV_PYTHON_PREFERENCE=only-system

WORKDIR /app

ENV PYTHONPATH=/app/module_backend_infra

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv sync

COPY ./module_backend_infra /app/module_backend_infra
COPY ./configs /app/configs

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "module_backend_infra.main:app", "--host", "0.0.0.0", "--port", "8000"]